[ecosystems.stac]
repos = [
    "stac-utils/pystac",
    "stac-utils/pystac-client",
    "stac-utils/stac-fastapi",
    "stac-utils/stactools",
]
top_contributors = [
    "lossyrob",
    "duckontheweb",
    "gadomski",
    "jsignell",
    "matthewhanson",
]

[contributors]
lossyrob = "Rob Emanuele"
duckontheweb = "Jon Duckworth"
gadomski = "Pete Gadomski"
jsignell = "Julia Signell"
matthewhanson = "Matthew Hanson"
