[ecosystems.pystac]
repos = [
    "stac-utils/pystac",
    "radiantearth/stac-spec",
    "radiantearth/stac-browser",
    "radiantearth/stac-api-spec",
    "radiantearth/stac-site",
    "stac-utils/pystac-client",
    "stac-utils/stac-fastapi",
    "stac-utils/stac-fastapi-pgstac",
    "stac-utils/stactools",
    "stac-utils/pgstac",
    "stac-utils/stac-server",
    "stac-utils/stac-layer",
]
top_contributors = [
    "lossyrob",
    "duckontheweb",
    "gadomski",
    "jsignell",
    "matthewhanson",
    "l0b0",
    "simonkassel",
    "schwehr",
    "volaya",
    "pjhartzell",
    "vincentsarago",
    "moradology",
    "m-mohr",
    "emmanuelmathot",
]

[contributors]
lossyrob = "Rob Emanuele"
duckontheweb = "Jon Duckworth"
gadomski = "Pete Gadomski"
jsignell = "Julia Signell"
matthewhanson = "Matthew Hanson"
vincentsarago = "Vincent Sarago"
moradology = "Nathan Zimmerman"
m-mohr = "Matthias Mohr"
emmanuelmathot = "Emmanuel Mathot"
l0b0 = "Victor Engmark"
simonkassel = "Simon Kassel"
schwehr = "Kurt Schwehr"
volaya = "Víctor Olaya"
pjhartzell = "Preston Hartzell"
